version: '3.9'

services:
  postgres-nest:
    image: postgres:16
    restart: always
    container_name: postgres-nest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - shared_pgdata:/var/lib/postgresql/data

  nest:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres-nest

  angular-app:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: angular-app
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./front:/angular-app
    environment:
      - STYLE=scss

volumes:
  shared_pgdata:
