version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - shared_pgdata:/var/lib/postgresql/data

  nest:
    image: nestjs/cli
    build: ./app
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      -

  front: